### ISSUE TITLE
Make seq_depth_th dependent on average abundance

### ISSUE THREAD

**Issue by joaovaleriano** [jsevo/mtist#3]
At the moment, the threshold for setting abundances to zero during dataset generation, `seq_depth_th`, is a constant. It could well be that, depending on the set of growth rates + interaction matrix, there could be a stable fixed point where one or more species have abundances close to or even below the `seq_depth_th` value.

One suggestion to avoid that is to make `seq_depth_th` dependent on the average abundance (which I'll call `avg_abun`) over all species in the system. Maybe something like `seq_depth_th = 0.001*avg_abun`.

**Comment by granthussey** [comment]
This is a good idea, but when we worked on this problem before, implementations of seq_depth doesn't actually change anything ... so we may need to work harder on this specific feature to get it to be biologically meaningful
