### ISSUE TITLE
in infer_mtist.prepare_data_for_inference unused  `n_timepoints` in line 88 should be _ 

### ISSUE THREAD

**Issue by jsevo** [jsevo/mtist#5]
This confused me for a second: 

`
    n_timepoints, n_species = X.shape
`

is actually not loading the time points for one time series, but timepoints * number of time series. Since unused, consider:

`
_, n_species = X.shape
`

**Comment by granthussey** [comment]
Fixed in a44a526dc20e27a74ee602b23ad254e7bdf560d6
